version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:5000
    volumes:
      - .:/app
    env_file: .env
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin_data:/var/lib/
    depends_on:
      - db
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'celery -A celery_config.celery_app worker --loglevel=info'
    depends_on:
      - redis
      - web
      - db
    networks:
      - app-network


  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'celery -A celery_config.celery_app beat --loglevel=info'
    depends_on:
      - redis
      - web
      - db
    networks:
      - app-network

  redis:
    image: redis
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - 6378:6379

volumes:
  pgdata:
  pgadmin_data:

networks:
  app-network:
    driver: bridge
