version: "3.7"

services:

  redis:
    container_name: redis_dev_container
    image: redis
    ports:
      - "6379:6379"
  flask_service:
    container_name: flask_dev_container
    restart: always
    image: flask
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./:/adsb_fdp
    environment:
      - FLASK_DEBUG=1
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  pgadmin:
      image: dpage/pgadmin4
      depends_on:
        - db
      ports:
        - "${PGADMIN_PORT}:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      volumes:
        - pgadmin_data:/var/lib/pgadmin/data
      restart: unless-stopped

volumes:
    postgres_data:
    pgadmin_data: