name: Continuous Integration
on:
  push:
    branches:
      - main
      - pipeline_setup
      - stage
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_DRIVER: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: 127.0.0.1
      DB_NAME: adsb_fdp
      DB_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start PostgreSQL service
        run: sudo service postgresql start

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest --buffer
